version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: harry
      POSTGRES_PASSWORD: rootroot
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
